### ISSUE TITLE
Chat mode not working in new build

### ISSUE THREAD

**Issue by sskohli01** [chrishayuk/mcp-cli#120]
Hi,
This command was working fine previously
mcp-cli chat --provider ollama --model qwen3 --server sqlite   
Usage: mcp-cli chat [OPTIONS] KWARGS
I tried giving a 'hi' at the end but then it didn't load the tools
mcp-cli chat --provider ollama --model qwen3 --server sqlite  hi

2025-05-16 10:57:08,979  ERROR     Timeout waiting for server initialization response (after 5.0s)
2025-05-16 10:57:08,979  ERROR     Error initializing stdio transport: 
{"timestamp": "2025-05-16T05:27:08.986652Z", "level": "ERROR", "message": "Failed to init sqlite", "logger": "chuk_tool_processor.mcp.stream_manager", "pid": 40926, "thread": 8516816768, "file": "context.py", "line": 212, "function": "_forward"}
2025-05-16 10:57:08,986  ERROR     Failed to init sqlite
{"timestamp": "2025-05-16T05:27:08.987845Z", "level": "INFO", "message": "StreamManager ready \u2013 0 server(s), 0 tool(s)", "logger": "chuk_tool_processor.mcp.stream_manager", "pid": 40926, "thread": 8516816768, "file": "context.py", "line": 212, "function": "_forward"}
2025-05-16 10:57:08,987  INFO      StreamManager ready – 0 server(s), 0 tool(s)
{"timestamp": "2025-05-16T05:27:09.000584Z", "level": "INFO", "message": "MCP registration complete \u2013 0 tool(s) available", "logger": "chuk_tool_processor.mcp.register", "pid": 40926, "thread": 8516816768, "file": "context.py", "line": 212, "function": "_forward"}
2025-05-16 10:57:09,000  INFO      MCP registration complete – 0 tool(s) available
{"timestamp": "2025-05-16T05:27:09.000743Z", "level": "INFO", "message": "MCP (stdio) initialised \u2013 0 tools registered into namespace 'stdio'", "logger": "chuk_tool_processor.mcp.setup_stdio", "pid": 40926, "thread": 8516816768, "file": "context.py", "line": 212, "function": "_forward"}
2025-05-16 10:57:09,000  INFO      MCP (stdio) initialised – 0 tools registered into namespace 'stdio'
⠼ Initializing chat context...2025-05-16 10:57:10,438  WARNING   Ollama client doesn't support set_host; api_base 'http://localhost:11434' will be ignored
No tools available. Chat functionality may be limited.
2025-05-16 10:57:10,440  WARNING   No tools found during initialization

**Comment by chrishayuk** [comment]
this should be fixed now

**Comment by princebelkovetz** [comment]
Hi @chrishayuk 

I'm encountering the same problem and wanted to follow up since the fix doesn't seem to resolve it in my setup.
I've verified I'm using the latest version from main branch. 
The error I get is the same as the error in the issue
